name: CI

on: 
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

  install:
    runs-on: ubuntu-latest

    needs: 
      - setup

    steps:
      - name: Install Dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest

    needs:
      - setup
      - install

    steps:
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    needs:
      - setup
      - install

    steps:
      - name: tests
        run: npm test

  build:
    runs-on: ubuntu-latest

    needs:
      - setup
      - install

    steps:
      - name: Build
        run: npm run build
